function [data, events ] = VPmonkey_importEyetrackingData(filename, dataLines)
%IMPORTFILE Import data from a text file
%  UNTITLED = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  UNTITLED = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Untitled = importfile("/home/rick/neuro/iannettilab/Projects/VP monkey/data/raw_dual2split/S06_MT/2022-6-10;15-53-2.txt", [38, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 12-Jun-2022 18:06:17

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [38, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 25);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["VarName1", "TotalTime", "DeltaTime", "X_Gaze", "Y_Gaze", "X_CorrectedGaze", "Y_CorrectedGaze", "Region", "PupilWidth", "PupilHeight", "Quality", "Fixation", "TotalTime1", "DeltaTime1", "X_Gaze1", "Y_Gaze1", "X_CorrectedGaze1", "Y_CorrectedGaze1", "Region1", "PupilWidth1", "PupilHeight1", "Quality1", "Fixation1", "Count", "Marker"];
opts.VariableTypes = ["double"	"double"	"char"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"char"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"double"	"string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Marker", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Marker", "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["VarName1", "TotalTime", "X_Gaze", "Y_Gaze", "X_CorrectedGaze", "Y_CorrectedGaze", "Region", "PupilWidth", "PupilHeight", "Quality", "Fixation", "TotalTime1", "X_Gaze1", "Y_Gaze1", "X_CorrectedGaze1", "Y_CorrectedGaze1", "Region1", "PupilWidth1", "PupilHeight1", "Quality1", "Fixation1", "Count"], "ThousandsSeparator", ",");

% Import the data
out = readtable(filename, opts);

% split events and data
indy_events = ~contains( [out.DeltaTime] , '.') & ~strcmp([out.DeltaTime] , 'STARTUP.BMP') ;
data =  out(~indy_events,:);
events = out(indy_events,:);

end